---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ee-supported-rhel8:latest'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8:latest'

dependencies:
  system: bindep.txt

additional_build_steps:
# Additional steps can be passed as a multi-line block or list.
  prepend: |
    RUN echo "Pre install commands."
    RUN pip3 install --upgrade pip setuptools
  append: |
    RUN echo "Post install commands."
    RUN pip3 list --format=freeze


